# Generated by Django 3.1.6 on 2021-02-11 14:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_staff', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='RegionalOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_staff', models.IntegerField()),
                ('issue', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('field_office', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='offices.fieldoffice')),
            ],
        ),
        migrations.CreateModel(
            name='HeadOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_staff', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('regional_office', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='offices.regionaloffice')),
            ],
        ),
    ]
