# Generated by Django 3.1.6 on 2021-02-11 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_auto_20210212_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headoffice',
            name='regional_office',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='field_office',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='issue',
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('description', models.TextField()),
                ('field_office', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='offices.fieldoffice')),
                ('regional_office', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='offices.regionaloffice')),
            ],
        ),
    ]
